### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_fink#15]
@JulienPeloton , can you do a 0.4.1 release? A user pointed out an issue with version conflicts in `elasticsearch-dsl` when using both `tom_antares` and `tom_fink`, so I narrowed the version requirements and upped the `tomtoolkit` verison.

**Comment by JulienPeloton** [comment]
Thanks @dmcollom for the fix! Do you mean 0.3.1 instead?

**Comment by JulienPeloton** [comment]
current version is 0.3

**Comment by dmcollom** [comment]
No, 0.3 has been released. Looks like I tagged a 0.4 a while back for [this commit](https://github.com/TOMToolkit/tom_fink/commit/82736eadb0688ab6626739d8fee5d97c4af2a41a), so the new one is 0.4.1.

**Comment by JulienPeloton** [comment]
Oh I see - you mean github release, not pypi. I will update both anyway and let you know

**Comment by JulienPeloton** [comment]
It is on pip, `pip install tom-fink` should install 0.4.1.

**Comment by dmcollom** [comment]
Great, thanks!
